FROM python:3.11-slim

RUN pip install --no-cache-dir mlflow==2.19.0
WORKDIR /app
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:////app/state/mlflow.db", "--serve-artifacts", "--artifacts-destination", "/app/mlruns"]
